import Head from "next/head";
import HomePage from "./HomePage";

export default function Home() {
  const Navbar = () => {
    return (
      <nav className="brown">
        <div className="nav-wrapper">
          <div className="container">
            <a href="#" className="brand-logo">
              Reactchain
            </a>
            <ul id="nav-mobile" className="right hide-on-med-and-down">
              <li>
                <a href="sass.html">Settings</a>
              </li>
              <li>
                <a href="collapsible.html">Create Transaction</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    );
  };

  return (
    <div>
      <Head>
        <title>Reactchain - Blockchain demo using React!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
        ></link>
      </Head>
      <Navbar />
      <HomePage />
    </div>
  );
}
